CREATE OR REPLACE SYNONYM COM_CFG_BUS_MODULE FOR ${common_schema}.COM_CFG_BUS_MODULE;

CREATE OR REPLACE SYNONYM COM_CFG_PROCESS_TYPE FOR ${bpm_schema}.COM_CFG_PROCESS_TYPE;

CREATE OR REPLACE SYNONYM COM_INF_ORGANIZATION FOR ${common_schema}.COM_INF_ORGANIZATION;

CREATE OR REPLACE SYNONYM COM_INF_SEQUENCE FOR ${common_schema}.COM_INF_SEQUENCE;

CREATE OR REPLACE SYNONYM COM_CFG_COMMON FOR ${common_schema}.COM_CFG_COMMON;

CREATE OR REPLACE SYNONYM COM_INF_CURRENCY_TYPE FOR ${common_schema}.COM_INF_CURRENCY_TYPE;

CREATE OR REPLACE SYNONYM HRM_INF_EMPLOYEE FOR ${hrm_schema}.HRM_INF_EMPLOYEE;

CREATE OR REPLACE SYNONYM CRM_INF_CUST_DOC FOR ${crm_schema}.CRM_INF_CUST_DOC;

CREATE OR REPLACE SYNONYM CRM_INF_CUST_ADDR FOR ${crm_schema}.CRM_INF_CUST_ADDR;

CREATE OR REPLACE SYNONYM CRM_INF_CUST FOR ${crm_schema}.CRM_INF_CUST;

CREATE OR REPLACE SYNONYM COM_CFG_MAIL_TEMPLATE FOR ${common_schema}.COM_CFG_MAIL_TEMPLATE;