spring.profiles.active=

#Application name
spring.application.name=tableau_proxy
info.app.name=tableau_proxy
info.app.version=1.0.0

#Tomcat server
server.port=80

#Tomcat server
server.shutdown=graceful
server.compression.enabled=true
server.error.whitelabel.enabled=false
server.tomcat.threads.max=200
#default 100 # Maximum queue length for incoming connection requests when all possible request processing threads are in use.
server.tomcat.accept-count=100
#default 10000 Maximum number of connections that the server accepts and processes at any given time.
server.tomcat.max-connections=10000



#multipart-file
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=100MB
#server.max-http-header-size=48KB

#OAuth2
whitelist.origin=http://localhost,http://localhost:4201,https://biportal.dev.ngvgroup.vn/,https://tableau-proxy.dev.ngvgroup.vn/
oauth2.accessTokenUri=http://10.1.27.143:8910/oauth/token
oauth2.jwtPublicKey=-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAw6EXqpn1UijPUjOhvr1rR/1wO00dzfkmKCs9+qb7rPv3JT6UIsqBpFSEWn4VCL1h8HlZ0IkeqDKBO/NOr4v7cCulrUhQBjHcy6s96SyIBIAE6kg5kwsLo14tm24fJ+SSy/DbJtfPsE/m03lTZ+e9bWYNYedBwZlWMkGMue1+U6wjSGPuORRk7VBubM21IAAedS5LsJ6uzsift5u3HYXb0vnM24ZGlnnQUaIZy/ZshZIajeggufCCxtbliDg7IiUTUjutxHI8M9RfMZpThdJng8oTtPmDrPxi4PJoXn0dSzCRgIuRckx4ot9IdPY2yJZGNEBh8AS1TMZ6tO4p+/D6vwIDAQAB-----END PUBLIC KEY-----
oauth2.url=http://10.1.27.43:8888/oauth2-server/oauth/token?grant_type=client_credentials
oauth2.username=bpm_user1
oauth2.password=123456

#Hikari DataSource and Pool
spring.datasource.url=jdbc:oracle:thin:@113.190.234.241:31521/ORCLPDB1
spring.datasource.username=QTDL_BUSINESS
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=100
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.poolName=HikariCP
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#Logging config
logging.config=classpath:log4j2.xml
logging.level.root=DEBUG
logging.level.vn.com.amc.qtdl.tableau_proxy=DEBUG
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.org.springframework.web=DEBUG

#kafka config
mb.kafka.brokers=10.10.0.31:9092
mb.kafka.group.id=bpm
mb.kafka.retry=1
mb.kafka.timeout=600
mb.kafka.topic.bpmLog=app-bpm-ind-audit
mb.kafka.topic.bpmEmail=app-bpm-ind-email
mb.kafka.topic.bpmError=app-bpm-ind-error

bpm.event.mode=debug
bpm.role.admin=BPM_ADMIN

#redis config
mb.redis.isCluster=true
mb.redis.host=bpm-redis-primary.dev-bpm.svc.cluster.local:6379,bpm-redis-replica.uat-bpm.svc.cluster.local:6379
mb.redis.timeout=1000
mb.redis.maxTotal=8
mb.redis.maxIdle=8
mb.redis.maxWait=1000

#ldap config
management.health.ldap.enabled=false
management.health.rabbit.enabled=false
database.username=data
server.port=8087
server.forward-headers-strategy=native

# --- Spring Cloud Gateway ---
spring.cloud.gateway.forwarded.enabled=false

# Route: upstream_route
spring.cloud.gateway.routes[0].id=upstream_route
# spring.cloud.gateway.routes[0].uri=https://tableau.dev.ngvgroup.vn
spring.cloud.gateway.routes[0].uri=http://10.10.0.32
spring.cloud.gateway.routes[0].predicates[0]=Path=/**
spring.cloud.gateway.routes[0].filters[0]=RemoveResponseHeader=X-Frame-Options
spring.cloud.gateway.routes[0].filters[1]=PreserveHostHeader
spring.cloud.gateway.routes[0].filters[2]=RemoveRequestHeader=X-Forwarded-Proto
spring.cloud.gateway.routes[0].filters[3]=RewritePath=/tableau/get-ticket, /trusted
spring.cloud.gateway.routes[0].filters[4]=RewriteResponseHeader=Location, http://tableau-proxy.dev.ngvgroup.vn, https://tableau-proxy.dev.ngvgroup.vn
#spring.cloud.gateway.routes[0].filters[5]=RemoveResponseHeader=Content-Disposition


spring.cloud.gateway.httpclient.pool.max-connections=200
spring.cloud.gateway.httpclient.pool.max-idle-time=30s
spring.cloud.gateway.httpclient.pool.acquire-timeout=5000
spring.cloud.gateway.httpclient.connect-timeout=10000
spring.cloud.gateway.httpclient.response-timeout=30000


app.url-tableau=https://tableau-proxy.dev.ngvgroup.vn/
app.url-portal=https://epas.dev.ngvgroup.vn/

#---Whitelist---
app.whitelist.paths=/tableau/get-ticket,/health
app.whitelist.pattern=.*\\.(css|js|jpg|jpeg|png|gif|woff2|woff|ttf|svg|ico)$|^/vizql/v_\\d+/javascripts/hybrid-window/min/index\\.html\\?id=[a-zA-Z0-9\\$\\-]+&moduleId=view_data$

cache.report.expire-minutes=3



