CREATE OR REPLACE SYNONYM "COM_INF_ORGANIZATION" FOR "${common_schema}"."COM_INF_ORGANIZATION";

CREATE OR REPLACE SYNONYM "COM_CFG_COMMON" FOR "${common_schema}"."COM_CFG_COMMON";

CREATE OR REPLACE SYNONYM "COM_CFG_PARAMETER" FOR "${common_schema}"."COM_CFG_PARAMETER";

CREATE OR REPLACE SYNONYM "COM_CFG_RESOURCE_MAPPING" FOR "${common_schema}"."COM_CFG_RESOURCE_MAPPING";

CREATE OR REPLACE SYNONYM "HRM_CFG_POSITION" FOR "${hrm_schema}"."HRM_CFG_POSITION";

CREATE OR REPLACE SYNONYM "HRM_INF_EMPLOYEE" FOR "${hrm_schema}"."HRM_INF_EMPLOYEE";

CREATE OR REPLACE SYNONYM "HRM_INF_EMPLOYEE_POSITION" FOR "${hrm_schema}"."HRM_INF_EMPLOYEE_POSITION";

