CREATE OR REPLACE SYNONYM COM_CFG_COMMON FOR "{common_schema}".COM_CFG_COMMON;

CREATE OR REPLACE SYNONYM COM_CFG_TEMPLATE FOR "{common_schema}".COM_CFG_TEMPLATE;

CREATE OR REPLACE SYNONYM COM_INF_AREA FOR "{common_schema}".COM_INF_AREA;

CREATE OR REPLACE SYNONYM COM_INF_ECONOMIC_TYPE FOR "{common_schema}".COM_INF_ECONOMIC_TYPE;

CREATE OR REPLACE SYNONYM COM_INF_INDUSTRY FOR "{common_schema}".COM_INF_INDUSTRY;
    
CREATE OR REPLACE SYNONYM COM_INF_ORGANIZATION FOR "{common_schema}".COM_INF_ORGANIZATION;

CREATE OR REPLACE SYNONYM COM_INF_PROVINCE FOR "{common_schema}".COM_INF_PROVINCE;

CREATE OR REPLACE SYNONYM COM_INF_WARD FOR "{common_schema}".COM_INF_WARD;