apiVersion: apps/v1
kind: Deployment
metadata:
  name: ncf-uat-bus-common-be-deployment
  namespace: ncf-uat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ncf-uat-bus-common-be
      environment: ncf-uat
  template:
    metadata:
      labels:
        app: ncf-uat-bus-common-be
        environment: ncf-uat
    spec:
      containers:
      - name: epas-bus-common-be
        image: localhost:32000/epas-bus-common-be:ncf-uat
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "ncf-uat"
---
apiVersion: v1
kind: Service
metadata:
  name: ncf-uat-bus-common-be-service
  namespace: ncf-uat
spec:
  selector:
    app: ncf-uat-bus-common-be
    environment: ncf-uat
  ports:
  - port: 8080
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ncf-uat-bus-common-be-ingress
  namespace: ncf-uat
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: public
  rules:
  - host: ncf.uat.ngvgroup.vn
    http:
      paths:
      - path: /api-bus-common(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: ncf-uat-bus-common-be-service
            port:
              number: 8080
