
  CREATE OR REPLACE EDITIONABLE SYNONYM "COM_CFG_RESOURCE_MAPPING" FOR "${common_schema}"."COM_CFG_RESOURCE_MAPPING";


  CREATE OR REPLACE EDITIONABLE SYNONYM "COM_INF_ORGANIZATION" FOR "${common_schema}"."COM_INF_ORGANIZATION";


  CREATE OR REPLACE EDITIONABLE SYNONYM "COM_CFG_PARAMETER" FOR "${common_schema}"."COM_CFG_PARAMETER";


  CREATE OR REPLACE EDITIONABLE SYNONYM "COM_CFG_COMMON" FOR "${common_schema}"."COM_CFG_COMMON";

