spring:
  application:
    name: category-service
  mvc:
    dispatch-options-request: true
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0

  datasource:
    url: jdbc:oracle:thin:@113.190.234.241:31521/ORCLPDB1
    username: EPAS_DEV_BUSINESS
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.0.31:31090/realms/EPAS_DEV
          jwk-set-uri: http://10.10.0.31:31090/realms/EPAS_DEV/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

server:
  port: 8183
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
bpm:
  core:
    cors:
      allowed-origins:
        - https://epas.dev.ngvgroup.vn,

      allowed-methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      exposed-headers:
        - Authorization
      allow-credentials: true
      max-age: 3600
    web:
      ignoring-paths:
        - /api-docs/**
        - /swagger-ui.html
        - /swagger-ui/**
        - /h2-console/**
        - /actuator/**
    oauth2:
      token-uri: http://10.10.0.31:31090/realms/EPAS_DEV/protocol/openid-connect/token
      client-id: epas_service
      client-secret: 30EiPJ7G5O9DWc8YroWViOWETiPxB29f
      cache-token: true
# Cấu hình Swagger
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
  packages-to-scan: com.naas.category_service
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
logging:
  config: classpath:log4j.xml

minio:
  url: 10.10.0.31:32010
  access-key: admin
  secret-key: admin123
  bucket: epas
#epas-common:
epas-common: https://epas.dev.ngvgroup.vn/api-common
bus-pcf: https://epas.dev.ngvgroup.vn/api-bus-pcf