spring:
  application:
    name: category-service
  mvc:
    dispatch-options-request: true
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0

  datasource:
    url: jdbc:oracle:thin:@113.190.234.241:31521/ORCLPDB1
    username: NCF_UAT_BUSINESS
    password: 123456
    driver-class-name: oracle.jdbc.OracleDriver

  jackson:
    time-zone: Asia/Ho_Chi_Minh

  jpa:
    hibernate:
      ddl-auto: none

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://10.10.0.31:31091/realms/NCF_UAT
          jwk-set-uri: http://10.10.0.31:31091/realms/NCF_UAT/protocol/openid-connect/certs

server:
  port: 8080
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
bpm:
  core:
    cors:
      allowed-origins:
        - https://epas.dev.ngvgroup.vn
    oauth2:
      token-uri: http://10.10.0.31:31091/realms/NCF_UAT/protocol/openid-connect/token
      client-id: epas_service
      client-secret: 30EiPJ7G5O9DWc8YroWViOWETiPxB29f
      cache-token: true
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    prometheus:
      enabled: true
logging:
  config: classpath:log4j.xml

minio:
  url: http://minio-api-ext.minio-operator.svc.cluster.local:9000
  access-key: admin
  secret-key: admin123
  bucket: epas

ncf-common: https://ncf.uat.ngvgroup.vn/api-common
ncf-business: https://ncf.uat.ngvgroup.vn/api-ncf-business



