pipeline {
    agent any
    environment {
        dockerImage = ''
        containerName = 'category-be'
    }
    tools {
        maven 'Maven'
    }

    stages {
        stage('Clone source') {
            steps {
                script {
                    echo 'Cloning repository...'
                    checkout scm
                }
            }
        }

        stage('Build Maven') {
            steps {
                script {
                    echo 'Building Spring Boot application...'
                    sh 'mvn clean package -DskipTests'
                }
            }
        }


        stage('Build and Deploy - Dev') {
            when {
                expression {
                    def branch = env.GIT_BRANCH?.replaceFirst(/^origin\//, '') ?: 'unknown'
                    echo "💡 Evaluating condition: branch=${branch}"
                    return branch == 'dev'
                }
            }
            environment {
                ENV = 'dev'
                PORT = '8302'
            }
            steps {
                script {
                    echo 'Creating Docker image for DEV...'
                    dockerImage = docker.build("${containerName}:${ENV}")

                    echo 'Stopping and removing old DEV container if exists...'
                    sh '''
                        if docker ps -a --filter "name=${containerName}-${ENV}" | grep -q ${containerName}-${ENV}; then
                            docker stop ${containerName}-${ENV} || true
                            docker rm ${containerName}-${ENV} || true
                        fi
                    '''

                    echo 'Starting Docker container for DEV...'
                    sh '''
                        docker run -d \
                        --name ${containerName}-${ENV} \
                        -p ${PORT}:8183 \
                        ${containerName}:${ENV}
                    '''
                }
            }
        }

        stage('Build and Deploy - UAT') {
            when {
                expression {
                    def branch = env.GIT_BRANCH?.replaceFirst(/^origin\//, '') ?: 'unknown'
                    echo "Evaluating condition: branch=${branch}"
                    return branch == 'main'
                }
            }
            environment {
                ENV = 'uat'
                PORT = '8202'
            }
            steps {
                script {
                    echo 'Creating Docker image for UAT...'
                    dockerImage = docker.build("${containerName}:${ENV}")

                    echo 'Stopping and removing old UAT container if exists...'
                    sh '''
                        if docker ps -a --filter "name=${containerName}-${ENV}" | grep -q ${containerName}-${ENV}; then
                            docker stop ${containerName}-${ENV} || true
                            docker rm ${containerName}-${ENV} || true
                        fi
                    '''

                    echo 'Starting Docker container for UAT...'
                    sh '''
                        docker run -d \
                        --name ${containerName}-${ENV} \
                        -p ${PORT}:8183 \
                        ${containerName}:${ENV}
                    '''

                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline execution failed!'
        }
        always {
            cleanWs()
        }
    }
}
