pipeline {
    agent any
    environment {
        dockerImage = ''
        containerName = 'epas-category-be'
        ENV = 'dev'
        PORT = '8302'
    }
    tools {
        maven 'Maven'
    }

    stages {
        stage('Clone source') {
            steps {
                script {
                    echo 'Cloning repository...'
                    checkout scm
                }
            }
        }

        stage('Build Maven') {
                    steps {
                        script {
                            echo 'Building Spring Boot application...'
                            sh 'mvn clean package -DskipTests --settings .mvn/settings.xml'
                        }
                    }
                }

        stage('Build and Deploy') {
            steps {
                script {
                    echo 'Creating Docker image...'
                    dockerImage = docker.build("${containerName}:${ENV}", "-f cicd/dev/Dockerfile .")

                    echo 'Stopping and removing old container if exists...'
                    sh '''
                        if docker ps -a --filter "name=${ENV}-${containerName}" | grep -q ${ENV}-${containerName}; then
                            docker stop ${ENV}-${containerName} || true
                            docker rm ${ENV}-${containerName} || true
                        fi
                    '''

                    echo 'Starting Docker container...'
                    sh '''
                        docker run -d \
                        --name ${ENV}-${containerName} \
                        -p ${PORT}:8302 \
                        ${containerName}:${ENV}
                    '''
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline executed successfully!'
        }
        failure {
            echo 'Pipeline execution failed!'
        }
        always {
            cleanWs()
        }
    }
}
