spring.application.name=bi_proxy


spring.datasource.url=jdbc:oracle:thin:@113.190.234.241:31521/ORCLPDB1
spring.datasource.username=EPAS_DEV_STATISTICAL
spring.datasource.password=123456
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver
spring.datasource.hikari.minimumIdle=5
spring.datasource.hikari.maximumPoolSize=100
spring.datasource.hikari.idleTimeout=30000
spring.datasource.hikari.poolName=HikariCP
spring.datasource.hikari.maxLifetime=2000000
spring.datasource.hikari.connectionTimeout=30000
spring.jackson.serialization.fail-on-empty-beans=false
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

# Consolidated from application.yaml
spring.main.web-application-type=servlet
# Keep application name consistent with project

# Spring Cloud Gateway (WebMVC)
spring.cloud.gateway.server.webmvc.routes[0].id=powerbi_proxy
spring.cloud.gateway.server.webmvc.routes[0].uri=http://10.10.0.33
# spring.cloud.gateway.server.webmvc.routes[0].uri=http://113.190.234.241:2024
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/**
# Header mapping tương tự Nginx
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=AddRequestHeader=Host,#{request.headers['host']}
spring.cloud.gateway.server.webmvc.routes[0].filters[1]=AddRequestHeader=X-Real-IP,#{request.remoteAddress.address.hostAddress}
spring.cloud.gateway.server.webmvc.routes[0].filters[2]=AddRequestHeader=X-Forwarded-For,#{request.remoteAddress.address.hostAddress}
spring.cloud.gateway.server.webmvc.routes[0].filters[3]=AddRequestHeader=X-Forwarded-Proto,http
spring.cloud.gateway.server.webmvc.routes[0].filters[4]=AddRequestHeader=Authorization,Basic YWRtaW5pc3RyYXRvcjpOZ3ZAMjMwNDIwMDg=
spring.cloud.gateway.server.webmvc.routes[0].filters[5]=RemoveResponseHeader=X-Frame-Options
spring.cloud.gateway.server.webmvc.routes[0].filters[6]=RemoveResponseHeader=Content-Security-Policy

# Server
server.port=8080
server.tomcat.relaxed-path-chars=[,],{,}
server.tomcat.relaxed-query-chars=[,],{,}

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG

# App URLs
# app.url-bi=http://10.10.0.33/
app.url-bi=powerbi-proxy.dev.ngvgroup.vn
# app.url-portal=http://localhost:4201/
#app.url-portal=http://localhost:3000/
app.url-portal=https://epas.dev.ngvgroup.vn/


