
  CREATE OR REPLACE EDITIONABLE SYNONYM "COM_CFG_RESOURCE_MAPPING" FOR "${common_schema}"."COM_CFG_RESOURCE_MAPPING";


  CREATE OR REPLACE EDITIONABLE SYNONYM "COM_INF_ORGANIZATION" FOR "${common_schema}"."COM_INF_ORGANIZATION";


  CREATE OR REPLACE EDITIONABLE SYNONYM "COM_INF_USER" FOR "${common_schema}"."COM_INF_USER";


  CREATE OR REPLACE EDITIONABLE SYNONYM "CTG_COM_COMMON" FOR "${common_schema}"."COM_CFG_COMMON";

